services:
  ollama:
    image: ollama/ollama:0.4.0-rc5
    volumes:
      - ./ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: -1
              capabilities: [gpu]
  open-webui:
    image: ghcr.io/open-webui/open-webui:0.3.35
    volumes:
      - ./open-webui:/app/backend/data
    ports:
      - "8080:8080"
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
      WEBUI_AUTH: false
    depends_on:
      - ollama
